spring:
  application:
    name: nacos-stock # 定义当前服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848 # 指定正在运行的Nacos服务器的位置
  datasource:
    url: jdbc:mysql://localhost:13306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 747641

dubbo:
  protocol:
    # port设置为-1，表示随机分配端口
    # 生成端口的规则是：从20880开始寻找可用端口，如果20880被占用，则尝试20881，以此类推，直到找到可用端口
    port: -1
    # 设置dubbo协议的名称，一般固定为dubbo
    name: dubbo
  registry:
    # 设置注册中心的地址
    address: nacos://localhost:18848
  consumer:
    # 设置当前项目启动时，是否检查服务提供者是否存在，一般设置为false，表示不检查，以减少因为服务提供者未启动而导致的启动失败
    check: false

seata:
  # 定义事务的分组,一般是以项目为单位的,不同项目用它来区分
  tx-service-group: csmall_group
  service:
    vgroup-mapping:
      # 设置csmall_group分组使用默认(default)的seata配置
      csmall_group: default
    grouplist:
      # 设置seata的ip和端口号位置
      default: localhost:18091