spring:
  application:
    name: nacos-order # 定义当前服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848 # 指定正在运行的Nacos服务器的位置
  datasource:
    url: jdbc:mysql://localhost:13306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 747641

dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:18848
  consumer:
    check: false

seata:
  # 定义事务的分组,一般是以项目为单位的,不同项目用它来区分
  tx-service-group: csmall_group
  service:
    vgroup-mapping:
      # 设置csmall_group分组使用默认(default)的seata配置
      csmall_group: default
    grouplist:
      # 设置seata的ip和端口号位置
      default: localhost:18091
