spring:
  application:
    # 设置当前项目的名称,这个名字会提交到Nacos,注册为当前微服务的名称
    name: nacos-business
  cloud:
    nacos:
      discovery:
        # 配置Nacos的位置,用于提交当前项目信息
        server-addr: localhost:18848
dubbo:
  protocol:
    # port设置为-1 表示当前dubbo框架使用自动寻找端口的功能
    # 生成端口的规则是从20880开始寻找可用端口,如果当前端口号占用,就尝试+1,直到找到可用端口为止
    port: -1
    # 设置连接的名称,一般固定为dubbo即可
    name: dubbo
  registry:
    # 指定当前项目dubbo注册中心的类型和位置
    address: nacos://localhost:18848
  consumer:
    # 设置当前项目启动时,是否检查本项目需要的所有服务都可用
    # 设置它的值为false,表示不检查,以减少启动时因为需要的服务不可用导致的错误
    check: false