# 配置ES的IP地址和端口号
#spring:elasticsearch.rest.uris=http://localhost:19200
spring:
  elasticsearch:
    rest:
      uris: http://localhost:19200

# 设置日志门槛
logging:
  level:
    cn:
      tedu:
        search: debug
  # SpringDataElasticsearch框架中日志输出专用类也要设置debug
    org:
      elasticsearch:
        client:
          RestClient: debug
